---
Name: silverstripe-forager
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Forager\Interfaces\BatchDocumentInterface.default:
    class: SilverStripe\Forager\Service\BatchProcessor
    constructor:
      configuration: '%$SilverStripe\Forager\Service\IndexConfiguration'

  SilverStripe\Forager\Interfaces\BatchDocumentInterface.dataobject:
    class: SilverStripe\Forager\DataObject\DataObjectBatchProcessor
    constructor:
      configuration: '%$SilverStripe\Forager\Service\IndexConfiguration'

  SilverStripe\Forager\Extensions\SearchServiceExtension:
    constructor:
      indexService: '%$SilverStripe\Forager\Interfaces\IndexingInterface'
      configuration: '%$SilverStripe\Forager\Service\IndexConfiguration'
      batchProcessor: '%$SilverStripe\Forager\Interfaces\BatchDocumentInterface.dataobject'

  SilverStripe\Forager\Tasks\SearchConfigure:
    constructor:
      indexService: '%$SilverStripe\Forager\Interfaces\IndexingInterface'

  SilverStripe\Forager\Tasks\SearchReindex:
    constructor:
      configuration: '%$SilverStripe\Forager\Service\IndexConfiguration'

  SilverStripe\Forager\Tasks\SearchClearIndex:
    constructor:
      configuration: '%$SilverStripe\Forager\Service\IndexConfiguration'

  SilverStripe\Forager\Service\DocumentFetchCreatorRegistry:
    constructor:
      dataObject: '%$SilverStripe\Forager\DataObject\DataObjectFetchCreator'

  SilverStripe\Forager\Service\IndexConfiguration:
    constructor:
      indexPrefix: '`SS_ENVIRONMENT_TYPE`'

  SilverStripe\Forager\Service\DocumentBuilder:
    constructor:
      configuration: '%$SilverStripe\Forager\Service\IndexConfiguration'
      registry: '%$SilverStripe\Forager\Service\DocumentFetchCreatorRegistry'
